all :
	cd common; make

clean :
	cd common; make clean
	cd md_OTvortex; make clean
	cd md_gMRI; make clean
	cd md_jet; make clean
	cd md_jet_car; make clean
	cd md_kh; make clean
	cd md_parker; make clean
	cd md_shktb; make clean
	rm -f *.a
