target : 
	cd cansnc; make
	cd bc; make
	cd common; make
	cd solver; make
	cd reconstruct; make
clean :
	cd cansnc; make clean
	cd bc; make clean
	cd common; make clean
	cd solver; make clean
	cd reconstruct; make clean
	cd md_Machida2006; make clean
	cd md_jet; make clean
	rm -f *.a
