target : 
	cd cansnc; make
	cd bc; make
	cd common; make
	cd solver; make
	cd reconstruct; make
clean :
	cd cansnc; make clean
	cd bc; make clean
	cd common; make clean
	cd solver; make clean
	cd reconstruct; make clean
#	cd md_AccretionDisk; make clean
	rm -f *.a
